# Generated by Django 5.1.1 on 2024-10-24 13:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('Matricula', models.CharField(max_length=200)),
                ('Contrasena', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Directivos',
            fields=[
                ('idDirectivos', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
                ('Apellidos', models.CharField(max_length=45)),
                ('Matricula', models.CharField(max_length=200)),
                ('Correo', models.CharField(max_length=150)),
                ('Contrasena', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idHorario', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Lunes', models.TimeField(blank=True, null=True)),
                ('Martes', models.TimeField(blank=True, null=True)),
                ('Miercoles', models.TimeField(blank=True, null=True)),
                ('Jueves', models.TimeField(blank=True, null=True)),
                ('Viernes', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoEscolar',
            fields=[
                ('idPeriodo', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=60)),
                ('FechaInicio', models.DateTimeField()),
                ('FechaFin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DiaAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_y_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('Tipo', models.CharField(max_length=45)),
                ('idHorario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAsistencias.horario')),
            ],
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('idJustificacion', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=300)),
                ('estado', models.CharField(max_length=50)),
                ('idDiaAsistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAsistencias.diaasistencia')),
            ],
        ),
        migrations.CreateModel(
            name='PDFhorario',
            fields=[
                ('idPDFhorario', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('FechaModificacion', models.DateTimeField()),
                ('Nombre', models.CharField(max_length=300)),
                ('horario_pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('idHorario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAsistencias.horario')),
            ],
        ),
        migrations.AddField(
            model_name='horario',
            name='idPeriodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAsistencias.periodoescolar'),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('idProfesor', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
                ('Apellidos', models.CharField(max_length=45)),
                ('Contrasena', models.CharField(max_length=200)),
                ('Matricula', models.CharField(max_length=200)),
                ('Correo', models.CharField(max_length=150)),
                ('imagen_rostro', models.CharField(blank=True, max_length=255, null=True)),
                ('idDirectivos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAsistencias.directivos')),
            ],
        ),
        migrations.AddField(
            model_name='horario',
            name='idProfesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAsistencias.profesor'),
        ),
    ]
