# Generated by Django 5.1.1 on 2024-11-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAsistencias', '0003_alter_periodoescolar_fechafin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodoescolar',
            name='Nombre',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
