# Generated by Django 5.1.1 on 2024-11-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAsistencias', '0004_alter_periodoescolar_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfhorario',
            name='horario_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
