# Generated by Django 5.1.1 on 2024-11-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAsistencias', '0005_alter_pdfhorario_horario_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfhorario',
            name='horario_pdf',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
